version: 2
jobs:
  build:
    docker:
      - image: nephosolutions/docker
    environment:
      - DOCKER_IMAGE_OWNER: nephosolutions
      - DOCKER_IMAGE_NAME: circleci
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/${DOCKER_IMAGE_OWNER}-${DOCKER_IMAGE_NAME}.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/${DOCKER_IMAGE_OWNER}-${DOCKER_IMAGE_NAME}.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME} -t ${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/${DOCKER_IMAGE_OWNER}-${DOCKER_IMAGE_NAME}.tar ${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME}
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/${DOCKER_IMAGE_OWNER}-${DOCKER_IMAGE_NAME}.tar
      - run:
          name: Test Docker image
          command: |
            for app in ansible aws gcloud packer terraform; do
              docker run --rm ${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME} ${app} --version
            done
            docker run --rm ${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME} kubectl version --client
      - deploy:
          name: Tag and push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

              docker tag "${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME}" "${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
              docker push "${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME}:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"

              docker push "${DOCKER_IMAGE_OWNER}/${DOCKER_IMAGE_NAME}"
            fi
